name = "chelsea-sunrise"
account_id = "40435c60b74ed167fa51f900ad0e30ae"
main = "./workers-site/index.js"

workers_dev = true

usage_model = "bundled"
compatibility_flags = []
compatibility_date = "2021-10-09"

[site]
bucket = "./public"

[env.prod]
name = "hello"